# Generated by Django 5.0.7 on 2024-07-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('editor', 'Редактор'), ('viewer', 'Просмотр'), ('admin', 'Администратор')], max_length=10),
        ),
    ]
