# Generated by Django 5.1 on 2024-10-16 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work_log', '0003_alter_journalentry_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
